#!/usr/bin/env sh

set -e

if [ ! -z "${AKHQ_CONFIGURATION}" ]; then
    echo "${AKHQ_CONFIGURATION}" > "${MICRONAUT_CONFIG_FILES}"
fi

# Read user-defined JVM options from jvm.options file
JVM_OPTS_FILE=${JVM_OPTS_FILE:-/app/jvm.options}
for JVM_OPT in `grep "^-" ${JVM_OPTS_FILE}`
do
  JAVA_OPTS="${JAVA_OPTS} ${JVM_OPT}"
done

export JWT_TOKEN=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c64)

exec java ${JAVA_OPTS} -cp /app/akhq.jar:${CLASSPATH} org.akhq.App
