language: java
install: true

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - nodejs
      - npm

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules

script:
  - set -e
  # Gradle
  - ./gradlew --console=plain test
  - ./gradlew --console=plain shadowJar
  # Docker Build
  - cp build/libs/kafkahq-*.jar docker/app/kafkahq.jar
  - docker build . -t $TRAVIS_COMMIT
  # Docker Tag
  - if [ ! -z "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker tag $TRAVIS_COMMIT tchiotludo/kafkahq:$TRAVIS_TAG;
      docker push tchiotludo/kafkahq:$TRAVIS_TAG;
    fi
  # Docker Branch
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker tag $TRAVIS_COMMIT tchiotludo/kafkahq:latest;
      docker push tchiotludo/kafkahq:latest;
    elif [ "$TRAVIS_BRANCH" == "dev" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker tag $TRAVIS_COMMIT tchiotludo/kafkahq:$TRAVIS_BRANCH;
      docker push tchiotludo/kafkahq:$TRAVIS_BRANCH;
    fi
  - set +e

deploy:
  - provider: releases
    api_key:
      secure: Zb/iCIzv0qe+Ka/A6U7wSKUZ8AlQFY8jm0Mla1hcFZTTLs95NmIudxozuJr+D9rO3hqnkkeh23nfaNzGYLD6elLpDaFn3UpI2caA/6mc4QqZQ3fiw+49LDDjaGNLm0pnKVnaPdbusc6giz2GMQYpXcngLNbGtXN4KGEghmnQKSP+oIreBllUJNbvIpBjTJnBT8/PJAmzO6WnJl6U7J4lP06GVyM8Rq7UvlQuYGXZMvks3hRxQAUsSMWhNlK95XHEJkpOqxDUJXM9i8bKKqyy9RYl+/BkupQPPpShTXVPXtz1TTmo5cE+K6TLNBJkpw7QtYHqpbAZpwaYiwyf9XaZiZF4CSK4ue64NfvAtXSrDnUPZq7F2hzkZ01xADxnx3Q306QD1AJ1pHTyubmIN9rc6P5IQHezh6pgvTCA9T5mDjmPxgul4ERi3z3u6IIEanEi8lvkY6ZiVDx+/xMitEFkExhJQN+i0DUCEBNe/GJYYNKt6o/tcp2ptFLVADXQs6i9jNklaVbA9fFh48L1jEDH4KxNT5LnmVtxRHfs8+edQAI4eA3ZONKXrIhAD3wG+xnvjfOtX1YBoCkLIq30G+kY+No0yGKuOMiLbq0vbiDilh1slytRaMr+PhhceFUr/wzWZLb0iZlnDatcKq9gjuMY7oMfMk3DNTgoY/gDqXWl66k=
    draft: true
    skip_cleanup: true
    file: docker/app/kafkahq.jar
    on:
      tags: true

notifications:
  slack:
    secure: Dtu4lLhzouYS7VuXkI4rf1rEFRp7GkNNE8VglYQjSmKF5/jXnvLkqyYPbeGRmlCqy42ja41ydf5w63AdQ9DjEMpRmOFw1K2G8nfFX3yoPm//uEZNaMkcewI1NBVP/JOidy4NvVAeDp5PkhHHg7Qwvd0u51OZ1ZIUwdwiIEIi+4Y4F/lTBVcupIO7Nub2/vcwEkzC4B1PvalqH9UNS2jXiI6HlQoNRD8MkSPzgkfDjmf3Jgjt66SgTRcRE5wdfXvvvoWep49/uGXvo8ZBtc/HvrUHoQS+zV0iwei9dNtIj5a6Zth/zWjVcvBdwxdnvVgYihjzjoMEowGUqQrciC0VTzXiRl9yd4ALk6Qb9Ey6Dh3KTgLlsmrz2vvIiVmNsWJ3z5vElogIM2p4WU/3sw2+IUaZQoxesAAKIXg++rt9IbJSwB1eOlgOW6KlDKGeHZv3KZWvcDdXmjWDcCcdtSL9BPGN2mDjFZNda+fcDvwjmnLEoO36mYLSRW27KoWD+JyMAkxRz+x6ZnSkBiMedOeYWvdsq7YUphppcO8mPJnapZtzDiKqiihn1/48qScDWV9nBoFgkF4yCy0/53RVvlbUXLLdCUtMjqmJLRBpbHA3jeBDuMco8ArURdg8dujuytxtGHn85GOiaP69oJBqzm9b1RHFBzfDicy9ueo6MT3YsYg=
