// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: complexWithBookInside.proto

package org.akhq.utils;

public final class ComplexWithBookInsideProto {
  private ComplexWithBookInsideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.akhq.utils.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string author = 2;</code>
     * @return The author.
     */
    java.lang.String getAuthor();
    /**
     * <code>string author = 2;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>.google.protobuf.DoubleValue price = 3;</code>
     * @return Whether the price field is set.
     */
    boolean hasPrice();
    /**
     * <code>.google.protobuf.DoubleValue price = 3;</code>
     * @return The price.
     */
    com.google.protobuf.DoubleValue getPrice();
    /**
     * <code>.google.protobuf.DoubleValue price = 3;</code>
     */
    com.google.protobuf.DoubleValueOrBuilder getPriceOrBuilder();
  }
  /**
   * Protobuf type {@code org.akhq.utils.Book}
   */
  public  static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.akhq.utils.Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      title_ = "";
      author_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Book();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.DoubleValue.Builder subBuilder = null;
              if (price_ != null) {
                subBuilder = price_.toBuilder();
              }
              price_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(price_);
                price_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.akhq.utils.ComplexWithBookInsideProto.Book.class, org.akhq.utils.ComplexWithBookInsideProto.Book.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object author_;
    /**
     * <code>string author = 2;</code>
     * @return The author.
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 2;</code>
     * @return The bytes for author.
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private com.google.protobuf.DoubleValue price_;
    /**
     * <code>.google.protobuf.DoubleValue price = 3;</code>
     * @return Whether the price field is set.
     */
    public boolean hasPrice() {
      return price_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue price = 3;</code>
     * @return The price.
     */
    public com.google.protobuf.DoubleValue getPrice() {
      return price_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : price_;
    }
    /**
     * <code>.google.protobuf.DoubleValue price = 3;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getPriceOrBuilder() {
      return getPrice();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (!getAuthorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, author_);
      }
      if (price_ != null) {
        output.writeMessage(3, getPrice());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (!getAuthorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, author_);
      }
      if (price_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPrice());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.akhq.utils.ComplexWithBookInsideProto.Book)) {
        return super.equals(obj);
      }
      org.akhq.utils.ComplexWithBookInsideProto.Book other = (org.akhq.utils.ComplexWithBookInsideProto.Book) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (hasPrice() != other.hasPrice()) return false;
      if (hasPrice()) {
        if (!getPrice()
            .equals(other.getPrice())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getPrice().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.akhq.utils.ComplexWithBookInsideProto.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.akhq.utils.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.akhq.utils.Book)
        org.akhq.utils.ComplexWithBookInsideProto.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_Book_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.akhq.utils.ComplexWithBookInsideProto.Book.class, org.akhq.utils.ComplexWithBookInsideProto.Book.Builder.class);
      }

      // Construct using org.akhq.utils.ComplexWithBookInsideProto.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        author_ = "";

        if (priceBuilder_ == null) {
          price_ = null;
        } else {
          price_ = null;
          priceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_Book_descriptor;
      }

      @java.lang.Override
      public org.akhq.utils.ComplexWithBookInsideProto.Book getDefaultInstanceForType() {
        return org.akhq.utils.ComplexWithBookInsideProto.Book.getDefaultInstance();
      }

      @java.lang.Override
      public org.akhq.utils.ComplexWithBookInsideProto.Book build() {
        org.akhq.utils.ComplexWithBookInsideProto.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.akhq.utils.ComplexWithBookInsideProto.Book buildPartial() {
        org.akhq.utils.ComplexWithBookInsideProto.Book result = new org.akhq.utils.ComplexWithBookInsideProto.Book(this);
        result.title_ = title_;
        result.author_ = author_;
        if (priceBuilder_ == null) {
          result.price_ = price_;
        } else {
          result.price_ = priceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.akhq.utils.ComplexWithBookInsideProto.Book) {
          return mergeFrom((org.akhq.utils.ComplexWithBookInsideProto.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.akhq.utils.ComplexWithBookInsideProto.Book other) {
        if (other == org.akhq.utils.ComplexWithBookInsideProto.Book.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        if (other.hasPrice()) {
          mergePrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.akhq.utils.ComplexWithBookInsideProto.Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.akhq.utils.ComplexWithBookInsideProto.Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>string author = 2;</code>
       * @return The author.
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author = 2;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 2;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>string author = 2;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        author_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.DoubleValue price_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> priceBuilder_;
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       * @return Whether the price field is set.
       */
      public boolean hasPrice() {
        return priceBuilder_ != null || price_ != null;
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       * @return The price.
       */
      public com.google.protobuf.DoubleValue getPrice() {
        if (priceBuilder_ == null) {
          return price_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : price_;
        } else {
          return priceBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      public Builder setPrice(com.google.protobuf.DoubleValue value) {
        if (priceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          price_ = value;
          onChanged();
        } else {
          priceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      public Builder setPrice(
          com.google.protobuf.DoubleValue.Builder builderForValue) {
        if (priceBuilder_ == null) {
          price_ = builderForValue.build();
          onChanged();
        } else {
          priceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      public Builder mergePrice(com.google.protobuf.DoubleValue value) {
        if (priceBuilder_ == null) {
          if (price_ != null) {
            price_ =
              com.google.protobuf.DoubleValue.newBuilder(price_).mergeFrom(value).buildPartial();
          } else {
            price_ = value;
          }
          onChanged();
        } else {
          priceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      public Builder clearPrice() {
        if (priceBuilder_ == null) {
          price_ = null;
          onChanged();
        } else {
          price_ = null;
          priceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      public com.google.protobuf.DoubleValue.Builder getPriceBuilder() {
        
        onChanged();
        return getPriceFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      public com.google.protobuf.DoubleValueOrBuilder getPriceOrBuilder() {
        if (priceBuilder_ != null) {
          return priceBuilder_.getMessageOrBuilder();
        } else {
          return price_ == null ?
              com.google.protobuf.DoubleValue.getDefaultInstance() : price_;
        }
      }
      /**
       * <code>.google.protobuf.DoubleValue price = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
          getPriceFieldBuilder() {
        if (priceBuilder_ == null) {
          priceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                  getPrice(),
                  getParentForChildren(),
                  isClean());
          price_ = null;
        }
        return priceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.akhq.utils.Book)
    }

    // @@protoc_insertion_point(class_scope:org.akhq.utils.Book)
    private static final org.akhq.utils.ComplexWithBookInsideProto.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.akhq.utils.ComplexWithBookInsideProto.Book();
    }

    public static org.akhq.utils.ComplexWithBookInsideProto.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @java.lang.Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.akhq.utils.ComplexWithBookInsideProto.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComplexWithBookInsideOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.akhq.utils.ComplexWithBookInside)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return Whether the album field is set.
     */
    boolean hasAlbum();
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return The album.
     */
    org.akhq.utils.AlbumProto.Album getAlbum();
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     */
    org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder();

    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return Whether the film field is set.
     */
    boolean hasFilm();
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return The film.
     */
    org.akhq.utils.FilmProto.Film getFilm();
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     */
    org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder();

    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return Whether the stringWrapper field is set.
     */
    boolean hasStringWrapper();
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return The stringWrapper.
     */
    com.google.protobuf.StringValue getStringWrapper();
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getStringWrapperOrBuilder();

    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return Whether the anything field is set.
     */
    boolean hasAnything();
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return The anything.
     */
    com.google.protobuf.Any getAnything();
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getAnythingOrBuilder();
  }
  /**
   * Protobuf type {@code org.akhq.utils.ComplexWithBookInside}
   */
  public  static final class ComplexWithBookInside extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.akhq.utils.ComplexWithBookInside)
      ComplexWithBookInsideOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComplexWithBookInside.newBuilder() to construct.
    private ComplexWithBookInside(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComplexWithBookInside() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComplexWithBookInside();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ComplexWithBookInside(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.akhq.utils.AlbumProto.Album.Builder subBuilder = null;
              if (album_ != null) {
                subBuilder = album_.toBuilder();
              }
              album_ = input.readMessage(org.akhq.utils.AlbumProto.Album.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(album_);
                album_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.akhq.utils.FilmProto.Film.Builder subBuilder = null;
              if (film_ != null) {
                subBuilder = film_.toBuilder();
              }
              film_ = input.readMessage(org.akhq.utils.FilmProto.Film.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(film_);
                film_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (stringWrapper_ != null) {
                subBuilder = stringWrapper_.toBuilder();
              }
              stringWrapper_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stringWrapper_);
                stringWrapper_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (anything_ != null) {
                subBuilder = anything_.toBuilder();
              }
              anything_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(anything_);
                anything_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_ComplexWithBookInside_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_ComplexWithBookInside_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.class, org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.Builder.class);
    }

    public static final int ALBUM_FIELD_NUMBER = 1;
    private org.akhq.utils.AlbumProto.Album album_;
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return Whether the album field is set.
     */
    public boolean hasAlbum() {
      return album_ != null;
    }
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return The album.
     */
    public org.akhq.utils.AlbumProto.Album getAlbum() {
      return album_ == null ? org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
    }
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     */
    public org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder() {
      return getAlbum();
    }

    public static final int FILM_FIELD_NUMBER = 2;
    private org.akhq.utils.FilmProto.Film film_;
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return Whether the film field is set.
     */
    public boolean hasFilm() {
      return film_ != null;
    }
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return The film.
     */
    public org.akhq.utils.FilmProto.Film getFilm() {
      return film_ == null ? org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
    }
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     */
    public org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder() {
      return getFilm();
    }

    public static final int STRINGWRAPPER_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue stringWrapper_;
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return Whether the stringWrapper field is set.
     */
    public boolean hasStringWrapper() {
      return stringWrapper_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return The stringWrapper.
     */
    public com.google.protobuf.StringValue getStringWrapper() {
      return stringWrapper_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringWrapper_;
    }
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringWrapperOrBuilder() {
      return getStringWrapper();
    }

    public static final int ANYTHING_FIELD_NUMBER = 4;
    private com.google.protobuf.Any anything_;
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return Whether the anything field is set.
     */
    public boolean hasAnything() {
      return anything_ != null;
    }
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return The anything.
     */
    public com.google.protobuf.Any getAnything() {
      return anything_ == null ? com.google.protobuf.Any.getDefaultInstance() : anything_;
    }
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAnythingOrBuilder() {
      return getAnything();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (album_ != null) {
        output.writeMessage(1, getAlbum());
      }
      if (film_ != null) {
        output.writeMessage(2, getFilm());
      }
      if (stringWrapper_ != null) {
        output.writeMessage(3, getStringWrapper());
      }
      if (anything_ != null) {
        output.writeMessage(4, getAnything());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (album_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAlbum());
      }
      if (film_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFilm());
      }
      if (stringWrapper_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStringWrapper());
      }
      if (anything_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAnything());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside)) {
        return super.equals(obj);
      }
      org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside other = (org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside) obj;

      if (hasAlbum() != other.hasAlbum()) return false;
      if (hasAlbum()) {
        if (!getAlbum()
            .equals(other.getAlbum())) return false;
      }
      if (hasFilm() != other.hasFilm()) return false;
      if (hasFilm()) {
        if (!getFilm()
            .equals(other.getFilm())) return false;
      }
      if (hasStringWrapper() != other.hasStringWrapper()) return false;
      if (hasStringWrapper()) {
        if (!getStringWrapper()
            .equals(other.getStringWrapper())) return false;
      }
      if (hasAnything() != other.hasAnything()) return false;
      if (hasAnything()) {
        if (!getAnything()
            .equals(other.getAnything())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasFilm()) {
        hash = (37 * hash) + FILM_FIELD_NUMBER;
        hash = (53 * hash) + getFilm().hashCode();
      }
      if (hasStringWrapper()) {
        hash = (37 * hash) + STRINGWRAPPER_FIELD_NUMBER;
        hash = (53 * hash) + getStringWrapper().hashCode();
      }
      if (hasAnything()) {
        hash = (37 * hash) + ANYTHING_FIELD_NUMBER;
        hash = (53 * hash) + getAnything().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.akhq.utils.ComplexWithBookInside}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.akhq.utils.ComplexWithBookInside)
        org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInsideOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_ComplexWithBookInside_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_ComplexWithBookInside_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.class, org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.Builder.class);
      }

      // Construct using org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (albumBuilder_ == null) {
          album_ = null;
        } else {
          album_ = null;
          albumBuilder_ = null;
        }
        if (filmBuilder_ == null) {
          film_ = null;
        } else {
          film_ = null;
          filmBuilder_ = null;
        }
        if (stringWrapperBuilder_ == null) {
          stringWrapper_ = null;
        } else {
          stringWrapper_ = null;
          stringWrapperBuilder_ = null;
        }
        if (anythingBuilder_ == null) {
          anything_ = null;
        } else {
          anything_ = null;
          anythingBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.akhq.utils.ComplexWithBookInsideProto.internal_static_org_akhq_utils_ComplexWithBookInside_descriptor;
      }

      @java.lang.Override
      public org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside getDefaultInstanceForType() {
        return org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.getDefaultInstance();
      }

      @java.lang.Override
      public org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside build() {
        org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside buildPartial() {
        org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside result = new org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside(this);
        if (albumBuilder_ == null) {
          result.album_ = album_;
        } else {
          result.album_ = albumBuilder_.build();
        }
        if (filmBuilder_ == null) {
          result.film_ = film_;
        } else {
          result.film_ = filmBuilder_.build();
        }
        if (stringWrapperBuilder_ == null) {
          result.stringWrapper_ = stringWrapper_;
        } else {
          result.stringWrapper_ = stringWrapperBuilder_.build();
        }
        if (anythingBuilder_ == null) {
          result.anything_ = anything_;
        } else {
          result.anything_ = anythingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside) {
          return mergeFrom((org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside other) {
        if (other == org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside.getDefaultInstance()) return this;
        if (other.hasAlbum()) {
          mergeAlbum(other.getAlbum());
        }
        if (other.hasFilm()) {
          mergeFilm(other.getFilm());
        }
        if (other.hasStringWrapper()) {
          mergeStringWrapper(other.getStringWrapper());
        }
        if (other.hasAnything()) {
          mergeAnything(other.getAnything());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.akhq.utils.AlbumProto.Album album_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder> albumBuilder_;
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       * @return Whether the album field is set.
       */
      public boolean hasAlbum() {
        return albumBuilder_ != null || album_ != null;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       * @return The album.
       */
      public org.akhq.utils.AlbumProto.Album getAlbum() {
        if (albumBuilder_ == null) {
          return album_ == null ? org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
        } else {
          return albumBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder setAlbum(org.akhq.utils.AlbumProto.Album value) {
        if (albumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          album_ = value;
          onChanged();
        } else {
          albumBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder setAlbum(
          org.akhq.utils.AlbumProto.Album.Builder builderForValue) {
        if (albumBuilder_ == null) {
          album_ = builderForValue.build();
          onChanged();
        } else {
          albumBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder mergeAlbum(org.akhq.utils.AlbumProto.Album value) {
        if (albumBuilder_ == null) {
          if (album_ != null) {
            album_ =
              org.akhq.utils.AlbumProto.Album.newBuilder(album_).mergeFrom(value).buildPartial();
          } else {
            album_ = value;
          }
          onChanged();
        } else {
          albumBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder clearAlbum() {
        if (albumBuilder_ == null) {
          album_ = null;
          onChanged();
        } else {
          album_ = null;
          albumBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public org.akhq.utils.AlbumProto.Album.Builder getAlbumBuilder() {
        
        onChanged();
        return getAlbumFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder() {
        if (albumBuilder_ != null) {
          return albumBuilder_.getMessageOrBuilder();
        } else {
          return album_ == null ?
              org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
        }
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder> 
          getAlbumFieldBuilder() {
        if (albumBuilder_ == null) {
          albumBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder>(
                  getAlbum(),
                  getParentForChildren(),
                  isClean());
          album_ = null;
        }
        return albumBuilder_;
      }

      private org.akhq.utils.FilmProto.Film film_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder> filmBuilder_;
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       * @return Whether the film field is set.
       */
      public boolean hasFilm() {
        return filmBuilder_ != null || film_ != null;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       * @return The film.
       */
      public org.akhq.utils.FilmProto.Film getFilm() {
        if (filmBuilder_ == null) {
          return film_ == null ? org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
        } else {
          return filmBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder setFilm(org.akhq.utils.FilmProto.Film value) {
        if (filmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          film_ = value;
          onChanged();
        } else {
          filmBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder setFilm(
          org.akhq.utils.FilmProto.Film.Builder builderForValue) {
        if (filmBuilder_ == null) {
          film_ = builderForValue.build();
          onChanged();
        } else {
          filmBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder mergeFilm(org.akhq.utils.FilmProto.Film value) {
        if (filmBuilder_ == null) {
          if (film_ != null) {
            film_ =
              org.akhq.utils.FilmProto.Film.newBuilder(film_).mergeFrom(value).buildPartial();
          } else {
            film_ = value;
          }
          onChanged();
        } else {
          filmBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder clearFilm() {
        if (filmBuilder_ == null) {
          film_ = null;
          onChanged();
        } else {
          film_ = null;
          filmBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public org.akhq.utils.FilmProto.Film.Builder getFilmBuilder() {
        
        onChanged();
        return getFilmFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder() {
        if (filmBuilder_ != null) {
          return filmBuilder_.getMessageOrBuilder();
        } else {
          return film_ == null ?
              org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
        }
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder> 
          getFilmFieldBuilder() {
        if (filmBuilder_ == null) {
          filmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder>(
                  getFilm(),
                  getParentForChildren(),
                  isClean());
          film_ = null;
        }
        return filmBuilder_;
      }

      private com.google.protobuf.StringValue stringWrapper_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringWrapperBuilder_;
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       * @return Whether the stringWrapper field is set.
       */
      public boolean hasStringWrapper() {
        return stringWrapperBuilder_ != null || stringWrapper_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       * @return The stringWrapper.
       */
      public com.google.protobuf.StringValue getStringWrapper() {
        if (stringWrapperBuilder_ == null) {
          return stringWrapper_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringWrapper_;
        } else {
          return stringWrapperBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder setStringWrapper(com.google.protobuf.StringValue value) {
        if (stringWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringWrapper_ = value;
          onChanged();
        } else {
          stringWrapperBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder setStringWrapper(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (stringWrapperBuilder_ == null) {
          stringWrapper_ = builderForValue.build();
          onChanged();
        } else {
          stringWrapperBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder mergeStringWrapper(com.google.protobuf.StringValue value) {
        if (stringWrapperBuilder_ == null) {
          if (stringWrapper_ != null) {
            stringWrapper_ =
              com.google.protobuf.StringValue.newBuilder(stringWrapper_).mergeFrom(value).buildPartial();
          } else {
            stringWrapper_ = value;
          }
          onChanged();
        } else {
          stringWrapperBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder clearStringWrapper() {
        if (stringWrapperBuilder_ == null) {
          stringWrapper_ = null;
          onChanged();
        } else {
          stringWrapper_ = null;
          stringWrapperBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getStringWrapperBuilder() {
        
        onChanged();
        return getStringWrapperFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getStringWrapperOrBuilder() {
        if (stringWrapperBuilder_ != null) {
          return stringWrapperBuilder_.getMessageOrBuilder();
        } else {
          return stringWrapper_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : stringWrapper_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getStringWrapperFieldBuilder() {
        if (stringWrapperBuilder_ == null) {
          stringWrapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getStringWrapper(),
                  getParentForChildren(),
                  isClean());
          stringWrapper_ = null;
        }
        return stringWrapperBuilder_;
      }

      private com.google.protobuf.Any anything_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> anythingBuilder_;
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       * @return Whether the anything field is set.
       */
      public boolean hasAnything() {
        return anythingBuilder_ != null || anything_ != null;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       * @return The anything.
       */
      public com.google.protobuf.Any getAnything() {
        if (anythingBuilder_ == null) {
          return anything_ == null ? com.google.protobuf.Any.getDefaultInstance() : anything_;
        } else {
          return anythingBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder setAnything(com.google.protobuf.Any value) {
        if (anythingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          anything_ = value;
          onChanged();
        } else {
          anythingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder setAnything(
          com.google.protobuf.Any.Builder builderForValue) {
        if (anythingBuilder_ == null) {
          anything_ = builderForValue.build();
          onChanged();
        } else {
          anythingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder mergeAnything(com.google.protobuf.Any value) {
        if (anythingBuilder_ == null) {
          if (anything_ != null) {
            anything_ =
              com.google.protobuf.Any.newBuilder(anything_).mergeFrom(value).buildPartial();
          } else {
            anything_ = value;
          }
          onChanged();
        } else {
          anythingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder clearAnything() {
        if (anythingBuilder_ == null) {
          anything_ = null;
          onChanged();
        } else {
          anything_ = null;
          anythingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public com.google.protobuf.Any.Builder getAnythingBuilder() {
        
        onChanged();
        return getAnythingFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getAnythingOrBuilder() {
        if (anythingBuilder_ != null) {
          return anythingBuilder_.getMessageOrBuilder();
        } else {
          return anything_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : anything_;
        }
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getAnythingFieldBuilder() {
        if (anythingBuilder_ == null) {
          anythingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getAnything(),
                  getParentForChildren(),
                  isClean());
          anything_ = null;
        }
        return anythingBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.akhq.utils.ComplexWithBookInside)
    }

    // @@protoc_insertion_point(class_scope:org.akhq.utils.ComplexWithBookInside)
    private static final org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside();
    }

    public static org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexWithBookInside>
        PARSER = new com.google.protobuf.AbstractParser<ComplexWithBookInside>() {
      @java.lang.Override
      public ComplexWithBookInside parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComplexWithBookInside(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ComplexWithBookInside> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexWithBookInside> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.akhq.utils.ComplexWithBookInsideProto.ComplexWithBookInside getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_akhq_utils_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_akhq_utils_Book_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_akhq_utils_ComplexWithBookInside_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_akhq_utils_ComplexWithBookInside_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033complexWithBookInside.proto\022\016org.akhq." +
      "utils\032\013album.proto\032\nfilm.proto\032\036google/p" +
      "rotobuf/wrappers.proto\032\031google/protobuf/" +
      "any.proto\"R\n\004Book\022\r\n\005title\030\001 \001(\t\022\016\n\006auth" +
      "or\030\002 \001(\t\022+\n\005price\030\003 \001(\0132\034.google.protobu" +
      "f.DoubleValue\"\276\001\n\025ComplexWithBookInside\022" +
      "$\n\005album\030\001 \001(\0132\025.org.akhq.utils.Album\022\"\n" +
      "\004film\030\002 \001(\0132\024.org.akhq.utils.Film\0223\n\rstr" +
      "ingWrapper\030\003 \001(\0132\034.google.protobuf.Strin" +
      "gValue\022&\n\010anything\030\004 \001(\0132\024.google.protob" +
      "uf.AnyB,\n\016org.akhq.utilsB\032ComplexWithBoo" +
      "kInsideProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.akhq.utils.AlbumProto.getDescriptor(),
          org.akhq.utils.FilmProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_org_akhq_utils_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_akhq_utils_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_akhq_utils_Book_descriptor,
        new java.lang.String[] { "Title", "Author", "Price", });
    internal_static_org_akhq_utils_ComplexWithBookInside_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_akhq_utils_ComplexWithBookInside_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_akhq_utils_ComplexWithBookInside_descriptor,
        new java.lang.String[] { "Album", "Film", "StringWrapper", "Anything", });
    org.akhq.utils.AlbumProto.getDescriptor();
    org.akhq.utils.FilmProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
