// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: complex.proto

package org.akhq.utils;

public final class ComplexProto {
  private ComplexProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.akhq.utils.Complex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return Whether the album field is set.
     */
    boolean hasAlbum();
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return The album.
     */
    org.akhq.utils.AlbumProto.Album getAlbum();
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     */
    org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder();

    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return Whether the film field is set.
     */
    boolean hasFilm();
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return The film.
     */
    org.akhq.utils.FilmProto.Film getFilm();
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     */
    org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder();

    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return Whether the stringWrapper field is set.
     */
    boolean hasStringWrapper();
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return The stringWrapper.
     */
    com.google.protobuf.StringValue getStringWrapper();
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getStringWrapperOrBuilder();

    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return Whether the anything field is set.
     */
    boolean hasAnything();
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return The anything.
     */
    com.google.protobuf.Any getAnything();
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getAnythingOrBuilder();
  }
  /**
   * Protobuf type {@code org.akhq.utils.Complex}
   */
  public  static final class Complex extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.akhq.utils.Complex)
      ComplexOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Complex.newBuilder() to construct.
    private Complex(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Complex() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Complex();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Complex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.akhq.utils.AlbumProto.Album.Builder subBuilder = null;
              if (album_ != null) {
                subBuilder = album_.toBuilder();
              }
              album_ = input.readMessage(org.akhq.utils.AlbumProto.Album.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(album_);
                album_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.akhq.utils.FilmProto.Film.Builder subBuilder = null;
              if (film_ != null) {
                subBuilder = film_.toBuilder();
              }
              film_ = input.readMessage(org.akhq.utils.FilmProto.Film.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(film_);
                film_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (stringWrapper_ != null) {
                subBuilder = stringWrapper_.toBuilder();
              }
              stringWrapper_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stringWrapper_);
                stringWrapper_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (anything_ != null) {
                subBuilder = anything_.toBuilder();
              }
              anything_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(anything_);
                anything_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.akhq.utils.ComplexProto.internal_static_org_akhq_utils_Complex_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.akhq.utils.ComplexProto.internal_static_org_akhq_utils_Complex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.akhq.utils.ComplexProto.Complex.class, org.akhq.utils.ComplexProto.Complex.Builder.class);
    }

    public static final int ALBUM_FIELD_NUMBER = 1;
    private org.akhq.utils.AlbumProto.Album album_;
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return Whether the album field is set.
     */
    public boolean hasAlbum() {
      return album_ != null;
    }
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return The album.
     */
    public org.akhq.utils.AlbumProto.Album getAlbum() {
      return album_ == null ? org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
    }
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     */
    public org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder() {
      return getAlbum();
    }

    public static final int FILM_FIELD_NUMBER = 2;
    private org.akhq.utils.FilmProto.Film film_;
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return Whether the film field is set.
     */
    public boolean hasFilm() {
      return film_ != null;
    }
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return The film.
     */
    public org.akhq.utils.FilmProto.Film getFilm() {
      return film_ == null ? org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
    }
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     */
    public org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder() {
      return getFilm();
    }

    public static final int STRINGWRAPPER_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue stringWrapper_;
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return Whether the stringWrapper field is set.
     */
    public boolean hasStringWrapper() {
      return stringWrapper_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     * @return The stringWrapper.
     */
    public com.google.protobuf.StringValue getStringWrapper() {
      return stringWrapper_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringWrapper_;
    }
    /**
     * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringWrapperOrBuilder() {
      return getStringWrapper();
    }

    public static final int ANYTHING_FIELD_NUMBER = 4;
    private com.google.protobuf.Any anything_;
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return Whether the anything field is set.
     */
    public boolean hasAnything() {
      return anything_ != null;
    }
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     * @return The anything.
     */
    public com.google.protobuf.Any getAnything() {
      return anything_ == null ? com.google.protobuf.Any.getDefaultInstance() : anything_;
    }
    /**
     * <code>.google.protobuf.Any anything = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAnythingOrBuilder() {
      return getAnything();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (album_ != null) {
        output.writeMessage(1, getAlbum());
      }
      if (film_ != null) {
        output.writeMessage(2, getFilm());
      }
      if (stringWrapper_ != null) {
        output.writeMessage(3, getStringWrapper());
      }
      if (anything_ != null) {
        output.writeMessage(4, getAnything());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (album_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAlbum());
      }
      if (film_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFilm());
      }
      if (stringWrapper_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStringWrapper());
      }
      if (anything_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAnything());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.akhq.utils.ComplexProto.Complex)) {
        return super.equals(obj);
      }
      org.akhq.utils.ComplexProto.Complex other = (org.akhq.utils.ComplexProto.Complex) obj;

      if (hasAlbum() != other.hasAlbum()) return false;
      if (hasAlbum()) {
        if (!getAlbum()
            .equals(other.getAlbum())) return false;
      }
      if (hasFilm() != other.hasFilm()) return false;
      if (hasFilm()) {
        if (!getFilm()
            .equals(other.getFilm())) return false;
      }
      if (hasStringWrapper() != other.hasStringWrapper()) return false;
      if (hasStringWrapper()) {
        if (!getStringWrapper()
            .equals(other.getStringWrapper())) return false;
      }
      if (hasAnything() != other.hasAnything()) return false;
      if (hasAnything()) {
        if (!getAnything()
            .equals(other.getAnything())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasFilm()) {
        hash = (37 * hash) + FILM_FIELD_NUMBER;
        hash = (53 * hash) + getFilm().hashCode();
      }
      if (hasStringWrapper()) {
        hash = (37 * hash) + STRINGWRAPPER_FIELD_NUMBER;
        hash = (53 * hash) + getStringWrapper().hashCode();
      }
      if (hasAnything()) {
        hash = (37 * hash) + ANYTHING_FIELD_NUMBER;
        hash = (53 * hash) + getAnything().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.ComplexProto.Complex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexProto.Complex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.ComplexProto.Complex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.akhq.utils.ComplexProto.Complex prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.akhq.utils.Complex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.akhq.utils.Complex)
        org.akhq.utils.ComplexProto.ComplexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.akhq.utils.ComplexProto.internal_static_org_akhq_utils_Complex_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.akhq.utils.ComplexProto.internal_static_org_akhq_utils_Complex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.akhq.utils.ComplexProto.Complex.class, org.akhq.utils.ComplexProto.Complex.Builder.class);
      }

      // Construct using org.akhq.utils.ComplexProto.Complex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (albumBuilder_ == null) {
          album_ = null;
        } else {
          album_ = null;
          albumBuilder_ = null;
        }
        if (filmBuilder_ == null) {
          film_ = null;
        } else {
          film_ = null;
          filmBuilder_ = null;
        }
        if (stringWrapperBuilder_ == null) {
          stringWrapper_ = null;
        } else {
          stringWrapper_ = null;
          stringWrapperBuilder_ = null;
        }
        if (anythingBuilder_ == null) {
          anything_ = null;
        } else {
          anything_ = null;
          anythingBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.akhq.utils.ComplexProto.internal_static_org_akhq_utils_Complex_descriptor;
      }

      @java.lang.Override
      public org.akhq.utils.ComplexProto.Complex getDefaultInstanceForType() {
        return org.akhq.utils.ComplexProto.Complex.getDefaultInstance();
      }

      @java.lang.Override
      public org.akhq.utils.ComplexProto.Complex build() {
        org.akhq.utils.ComplexProto.Complex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.akhq.utils.ComplexProto.Complex buildPartial() {
        org.akhq.utils.ComplexProto.Complex result = new org.akhq.utils.ComplexProto.Complex(this);
        if (albumBuilder_ == null) {
          result.album_ = album_;
        } else {
          result.album_ = albumBuilder_.build();
        }
        if (filmBuilder_ == null) {
          result.film_ = film_;
        } else {
          result.film_ = filmBuilder_.build();
        }
        if (stringWrapperBuilder_ == null) {
          result.stringWrapper_ = stringWrapper_;
        } else {
          result.stringWrapper_ = stringWrapperBuilder_.build();
        }
        if (anythingBuilder_ == null) {
          result.anything_ = anything_;
        } else {
          result.anything_ = anythingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.akhq.utils.ComplexProto.Complex) {
          return mergeFrom((org.akhq.utils.ComplexProto.Complex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.akhq.utils.ComplexProto.Complex other) {
        if (other == org.akhq.utils.ComplexProto.Complex.getDefaultInstance()) return this;
        if (other.hasAlbum()) {
          mergeAlbum(other.getAlbum());
        }
        if (other.hasFilm()) {
          mergeFilm(other.getFilm());
        }
        if (other.hasStringWrapper()) {
          mergeStringWrapper(other.getStringWrapper());
        }
        if (other.hasAnything()) {
          mergeAnything(other.getAnything());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.akhq.utils.ComplexProto.Complex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.akhq.utils.ComplexProto.Complex) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.akhq.utils.AlbumProto.Album album_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder> albumBuilder_;
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       * @return Whether the album field is set.
       */
      public boolean hasAlbum() {
        return albumBuilder_ != null || album_ != null;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       * @return The album.
       */
      public org.akhq.utils.AlbumProto.Album getAlbum() {
        if (albumBuilder_ == null) {
          return album_ == null ? org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
        } else {
          return albumBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder setAlbum(org.akhq.utils.AlbumProto.Album value) {
        if (albumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          album_ = value;
          onChanged();
        } else {
          albumBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder setAlbum(
          org.akhq.utils.AlbumProto.Album.Builder builderForValue) {
        if (albumBuilder_ == null) {
          album_ = builderForValue.build();
          onChanged();
        } else {
          albumBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder mergeAlbum(org.akhq.utils.AlbumProto.Album value) {
        if (albumBuilder_ == null) {
          if (album_ != null) {
            album_ =
              org.akhq.utils.AlbumProto.Album.newBuilder(album_).mergeFrom(value).buildPartial();
          } else {
            album_ = value;
          }
          onChanged();
        } else {
          albumBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder clearAlbum() {
        if (albumBuilder_ == null) {
          album_ = null;
          onChanged();
        } else {
          album_ = null;
          albumBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public org.akhq.utils.AlbumProto.Album.Builder getAlbumBuilder() {
        
        onChanged();
        return getAlbumFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder() {
        if (albumBuilder_ != null) {
          return albumBuilder_.getMessageOrBuilder();
        } else {
          return album_ == null ?
              org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
        }
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder> 
          getAlbumFieldBuilder() {
        if (albumBuilder_ == null) {
          albumBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder>(
                  getAlbum(),
                  getParentForChildren(),
                  isClean());
          album_ = null;
        }
        return albumBuilder_;
      }

      private org.akhq.utils.FilmProto.Film film_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder> filmBuilder_;
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       * @return Whether the film field is set.
       */
      public boolean hasFilm() {
        return filmBuilder_ != null || film_ != null;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       * @return The film.
       */
      public org.akhq.utils.FilmProto.Film getFilm() {
        if (filmBuilder_ == null) {
          return film_ == null ? org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
        } else {
          return filmBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder setFilm(org.akhq.utils.FilmProto.Film value) {
        if (filmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          film_ = value;
          onChanged();
        } else {
          filmBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder setFilm(
          org.akhq.utils.FilmProto.Film.Builder builderForValue) {
        if (filmBuilder_ == null) {
          film_ = builderForValue.build();
          onChanged();
        } else {
          filmBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder mergeFilm(org.akhq.utils.FilmProto.Film value) {
        if (filmBuilder_ == null) {
          if (film_ != null) {
            film_ =
              org.akhq.utils.FilmProto.Film.newBuilder(film_).mergeFrom(value).buildPartial();
          } else {
            film_ = value;
          }
          onChanged();
        } else {
          filmBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder clearFilm() {
        if (filmBuilder_ == null) {
          film_ = null;
          onChanged();
        } else {
          film_ = null;
          filmBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public org.akhq.utils.FilmProto.Film.Builder getFilmBuilder() {
        
        onChanged();
        return getFilmFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder() {
        if (filmBuilder_ != null) {
          return filmBuilder_.getMessageOrBuilder();
        } else {
          return film_ == null ?
              org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
        }
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder> 
          getFilmFieldBuilder() {
        if (filmBuilder_ == null) {
          filmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder>(
                  getFilm(),
                  getParentForChildren(),
                  isClean());
          film_ = null;
        }
        return filmBuilder_;
      }

      private com.google.protobuf.StringValue stringWrapper_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringWrapperBuilder_;
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       * @return Whether the stringWrapper field is set.
       */
      public boolean hasStringWrapper() {
        return stringWrapperBuilder_ != null || stringWrapper_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       * @return The stringWrapper.
       */
      public com.google.protobuf.StringValue getStringWrapper() {
        if (stringWrapperBuilder_ == null) {
          return stringWrapper_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringWrapper_;
        } else {
          return stringWrapperBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder setStringWrapper(com.google.protobuf.StringValue value) {
        if (stringWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringWrapper_ = value;
          onChanged();
        } else {
          stringWrapperBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder setStringWrapper(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (stringWrapperBuilder_ == null) {
          stringWrapper_ = builderForValue.build();
          onChanged();
        } else {
          stringWrapperBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder mergeStringWrapper(com.google.protobuf.StringValue value) {
        if (stringWrapperBuilder_ == null) {
          if (stringWrapper_ != null) {
            stringWrapper_ =
              com.google.protobuf.StringValue.newBuilder(stringWrapper_).mergeFrom(value).buildPartial();
          } else {
            stringWrapper_ = value;
          }
          onChanged();
        } else {
          stringWrapperBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public Builder clearStringWrapper() {
        if (stringWrapperBuilder_ == null) {
          stringWrapper_ = null;
          onChanged();
        } else {
          stringWrapper_ = null;
          stringWrapperBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getStringWrapperBuilder() {
        
        onChanged();
        return getStringWrapperFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getStringWrapperOrBuilder() {
        if (stringWrapperBuilder_ != null) {
          return stringWrapperBuilder_.getMessageOrBuilder();
        } else {
          return stringWrapper_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : stringWrapper_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue stringWrapper = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getStringWrapperFieldBuilder() {
        if (stringWrapperBuilder_ == null) {
          stringWrapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getStringWrapper(),
                  getParentForChildren(),
                  isClean());
          stringWrapper_ = null;
        }
        return stringWrapperBuilder_;
      }

      private com.google.protobuf.Any anything_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> anythingBuilder_;
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       * @return Whether the anything field is set.
       */
      public boolean hasAnything() {
        return anythingBuilder_ != null || anything_ != null;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       * @return The anything.
       */
      public com.google.protobuf.Any getAnything() {
        if (anythingBuilder_ == null) {
          return anything_ == null ? com.google.protobuf.Any.getDefaultInstance() : anything_;
        } else {
          return anythingBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder setAnything(com.google.protobuf.Any value) {
        if (anythingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          anything_ = value;
          onChanged();
        } else {
          anythingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder setAnything(
          com.google.protobuf.Any.Builder builderForValue) {
        if (anythingBuilder_ == null) {
          anything_ = builderForValue.build();
          onChanged();
        } else {
          anythingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder mergeAnything(com.google.protobuf.Any value) {
        if (anythingBuilder_ == null) {
          if (anything_ != null) {
            anything_ =
              com.google.protobuf.Any.newBuilder(anything_).mergeFrom(value).buildPartial();
          } else {
            anything_ = value;
          }
          onChanged();
        } else {
          anythingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public Builder clearAnything() {
        if (anythingBuilder_ == null) {
          anything_ = null;
          onChanged();
        } else {
          anything_ = null;
          anythingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public com.google.protobuf.Any.Builder getAnythingBuilder() {
        
        onChanged();
        return getAnythingFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getAnythingOrBuilder() {
        if (anythingBuilder_ != null) {
          return anythingBuilder_.getMessageOrBuilder();
        } else {
          return anything_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : anything_;
        }
      }
      /**
       * <code>.google.protobuf.Any anything = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getAnythingFieldBuilder() {
        if (anythingBuilder_ == null) {
          anythingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getAnything(),
                  getParentForChildren(),
                  isClean());
          anything_ = null;
        }
        return anythingBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.akhq.utils.Complex)
    }

    // @@protoc_insertion_point(class_scope:org.akhq.utils.Complex)
    private static final org.akhq.utils.ComplexProto.Complex DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.akhq.utils.ComplexProto.Complex();
    }

    public static org.akhq.utils.ComplexProto.Complex getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Complex>
        PARSER = new com.google.protobuf.AbstractParser<Complex>() {
      @java.lang.Override
      public Complex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Complex(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Complex> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Complex> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.akhq.utils.ComplexProto.Complex getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_akhq_utils_Complex_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_akhq_utils_Complex_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcomplex.proto\022\016org.akhq.utils\032\013album.p" +
      "roto\032\nfilm.proto\032\036google/protobuf/wrappe" +
      "rs.proto\032\031google/protobuf/any.proto\"\260\001\n\007" +
      "Complex\022$\n\005album\030\001 \001(\0132\025.org.akhq.utils." +
      "Album\022\"\n\004film\030\002 \001(\0132\024.org.akhq.utils.Fil" +
      "m\0223\n\rstringWrapper\030\003 \001(\0132\034.google.protob" +
      "uf.StringValue\022&\n\010anything\030\004 \001(\0132\024.googl" +
      "e.protobuf.AnyB\036\n\016org.akhq.utilsB\014Comple" +
      "xProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.akhq.utils.AlbumProto.getDescriptor(),
          org.akhq.utils.FilmProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_org_akhq_utils_Complex_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_akhq_utils_Complex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_akhq_utils_Complex_descriptor,
        new java.lang.String[] { "Album", "Film", "StringWrapper", "Anything", });
    org.akhq.utils.AlbumProto.getDescriptor();
    org.akhq.utils.FilmProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
