// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multipleLayerComplex.proto

package org.akhq.utils;

public final class MultipleLayerComplexProto {
  private MultipleLayerComplexProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultipleLayerComplexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.akhq.utils.MultipleLayerComplex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return Whether the album field is set.
     */
    boolean hasAlbum();
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return The album.
     */
    org.akhq.utils.AlbumProto.Album getAlbum();
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     */
    org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder();

    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return Whether the film field is set.
     */
    boolean hasFilm();
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return The film.
     */
    org.akhq.utils.FilmProto.Film getFilm();
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     */
    org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder();

    /**
     * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
     * @return Whether the complex field is set.
     */
    boolean hasComplex();
    /**
     * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
     * @return The complex.
     */
    org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside getComplex();
    /**
     * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
     */
    org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutsideOrBuilder getComplexOrBuilder();
  }
  /**
   * Protobuf type {@code org.akhq.utils.MultipleLayerComplex}
   */
  public  static final class MultipleLayerComplex extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.akhq.utils.MultipleLayerComplex)
      MultipleLayerComplexOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultipleLayerComplex.newBuilder() to construct.
    private MultipleLayerComplex(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultipleLayerComplex() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MultipleLayerComplex();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultipleLayerComplex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.akhq.utils.AlbumProto.Album.Builder subBuilder = null;
              if (album_ != null) {
                subBuilder = album_.toBuilder();
              }
              album_ = input.readMessage(org.akhq.utils.AlbumProto.Album.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(album_);
                album_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.akhq.utils.FilmProto.Film.Builder subBuilder = null;
              if (film_ != null) {
                subBuilder = film_.toBuilder();
              }
              film_ = input.readMessage(org.akhq.utils.FilmProto.Film.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(film_);
                film_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.Builder subBuilder = null;
              if (complex_ != null) {
                subBuilder = complex_.toBuilder();
              }
              complex_ = input.readMessage(org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(complex_);
                complex_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.akhq.utils.MultipleLayerComplexProto.internal_static_org_akhq_utils_MultipleLayerComplex_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.akhq.utils.MultipleLayerComplexProto.internal_static_org_akhq_utils_MultipleLayerComplex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.class, org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.Builder.class);
    }

    public static final int ALBUM_FIELD_NUMBER = 1;
    private org.akhq.utils.AlbumProto.Album album_;
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return Whether the album field is set.
     */
    public boolean hasAlbum() {
      return album_ != null;
    }
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     * @return The album.
     */
    public org.akhq.utils.AlbumProto.Album getAlbum() {
      return album_ == null ? org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
    }
    /**
     * <code>.org.akhq.utils.Album album = 1;</code>
     */
    public org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder() {
      return getAlbum();
    }

    public static final int FILM_FIELD_NUMBER = 2;
    private org.akhq.utils.FilmProto.Film film_;
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return Whether the film field is set.
     */
    public boolean hasFilm() {
      return film_ != null;
    }
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     * @return The film.
     */
    public org.akhq.utils.FilmProto.Film getFilm() {
      return film_ == null ? org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
    }
    /**
     * <code>.org.akhq.utils.Film film = 2;</code>
     */
    public org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder() {
      return getFilm();
    }

    public static final int COMPLEX_FIELD_NUMBER = 3;
    private org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside complex_;
    /**
     * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
     * @return Whether the complex field is set.
     */
    public boolean hasComplex() {
      return complex_ != null;
    }
    /**
     * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
     * @return The complex.
     */
    public org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside getComplex() {
      return complex_ == null ? org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.getDefaultInstance() : complex_;
    }
    /**
     * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
     */
    public org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutsideOrBuilder getComplexOrBuilder() {
      return getComplex();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (album_ != null) {
        output.writeMessage(1, getAlbum());
      }
      if (film_ != null) {
        output.writeMessage(2, getFilm());
      }
      if (complex_ != null) {
        output.writeMessage(3, getComplex());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (album_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAlbum());
      }
      if (film_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFilm());
      }
      if (complex_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getComplex());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex)) {
        return super.equals(obj);
      }
      org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex other = (org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex) obj;

      if (hasAlbum() != other.hasAlbum()) return false;
      if (hasAlbum()) {
        if (!getAlbum()
            .equals(other.getAlbum())) return false;
      }
      if (hasFilm() != other.hasFilm()) return false;
      if (hasFilm()) {
        if (!getFilm()
            .equals(other.getFilm())) return false;
      }
      if (hasComplex() != other.hasComplex()) return false;
      if (hasComplex()) {
        if (!getComplex()
            .equals(other.getComplex())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasFilm()) {
        hash = (37 * hash) + FILM_FIELD_NUMBER;
        hash = (53 * hash) + getFilm().hashCode();
      }
      if (hasComplex()) {
        hash = (37 * hash) + COMPLEX_FIELD_NUMBER;
        hash = (53 * hash) + getComplex().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.akhq.utils.MultipleLayerComplex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.akhq.utils.MultipleLayerComplex)
        org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.akhq.utils.MultipleLayerComplexProto.internal_static_org_akhq_utils_MultipleLayerComplex_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.akhq.utils.MultipleLayerComplexProto.internal_static_org_akhq_utils_MultipleLayerComplex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.class, org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.Builder.class);
      }

      // Construct using org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (albumBuilder_ == null) {
          album_ = null;
        } else {
          album_ = null;
          albumBuilder_ = null;
        }
        if (filmBuilder_ == null) {
          film_ = null;
        } else {
          film_ = null;
          filmBuilder_ = null;
        }
        if (complexBuilder_ == null) {
          complex_ = null;
        } else {
          complex_ = null;
          complexBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.akhq.utils.MultipleLayerComplexProto.internal_static_org_akhq_utils_MultipleLayerComplex_descriptor;
      }

      @java.lang.Override
      public org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex getDefaultInstanceForType() {
        return org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.getDefaultInstance();
      }

      @java.lang.Override
      public org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex build() {
        org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex buildPartial() {
        org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex result = new org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex(this);
        if (albumBuilder_ == null) {
          result.album_ = album_;
        } else {
          result.album_ = albumBuilder_.build();
        }
        if (filmBuilder_ == null) {
          result.film_ = film_;
        } else {
          result.film_ = filmBuilder_.build();
        }
        if (complexBuilder_ == null) {
          result.complex_ = complex_;
        } else {
          result.complex_ = complexBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex) {
          return mergeFrom((org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex other) {
        if (other == org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex.getDefaultInstance()) return this;
        if (other.hasAlbum()) {
          mergeAlbum(other.getAlbum());
        }
        if (other.hasFilm()) {
          mergeFilm(other.getFilm());
        }
        if (other.hasComplex()) {
          mergeComplex(other.getComplex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.akhq.utils.AlbumProto.Album album_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder> albumBuilder_;
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       * @return Whether the album field is set.
       */
      public boolean hasAlbum() {
        return albumBuilder_ != null || album_ != null;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       * @return The album.
       */
      public org.akhq.utils.AlbumProto.Album getAlbum() {
        if (albumBuilder_ == null) {
          return album_ == null ? org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
        } else {
          return albumBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder setAlbum(org.akhq.utils.AlbumProto.Album value) {
        if (albumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          album_ = value;
          onChanged();
        } else {
          albumBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder setAlbum(
          org.akhq.utils.AlbumProto.Album.Builder builderForValue) {
        if (albumBuilder_ == null) {
          album_ = builderForValue.build();
          onChanged();
        } else {
          albumBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder mergeAlbum(org.akhq.utils.AlbumProto.Album value) {
        if (albumBuilder_ == null) {
          if (album_ != null) {
            album_ =
              org.akhq.utils.AlbumProto.Album.newBuilder(album_).mergeFrom(value).buildPartial();
          } else {
            album_ = value;
          }
          onChanged();
        } else {
          albumBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public Builder clearAlbum() {
        if (albumBuilder_ == null) {
          album_ = null;
          onChanged();
        } else {
          album_ = null;
          albumBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public org.akhq.utils.AlbumProto.Album.Builder getAlbumBuilder() {
        
        onChanged();
        return getAlbumFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      public org.akhq.utils.AlbumProto.AlbumOrBuilder getAlbumOrBuilder() {
        if (albumBuilder_ != null) {
          return albumBuilder_.getMessageOrBuilder();
        } else {
          return album_ == null ?
              org.akhq.utils.AlbumProto.Album.getDefaultInstance() : album_;
        }
      }
      /**
       * <code>.org.akhq.utils.Album album = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder> 
          getAlbumFieldBuilder() {
        if (albumBuilder_ == null) {
          albumBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.AlbumProto.Album, org.akhq.utils.AlbumProto.Album.Builder, org.akhq.utils.AlbumProto.AlbumOrBuilder>(
                  getAlbum(),
                  getParentForChildren(),
                  isClean());
          album_ = null;
        }
        return albumBuilder_;
      }

      private org.akhq.utils.FilmProto.Film film_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder> filmBuilder_;
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       * @return Whether the film field is set.
       */
      public boolean hasFilm() {
        return filmBuilder_ != null || film_ != null;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       * @return The film.
       */
      public org.akhq.utils.FilmProto.Film getFilm() {
        if (filmBuilder_ == null) {
          return film_ == null ? org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
        } else {
          return filmBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder setFilm(org.akhq.utils.FilmProto.Film value) {
        if (filmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          film_ = value;
          onChanged();
        } else {
          filmBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder setFilm(
          org.akhq.utils.FilmProto.Film.Builder builderForValue) {
        if (filmBuilder_ == null) {
          film_ = builderForValue.build();
          onChanged();
        } else {
          filmBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder mergeFilm(org.akhq.utils.FilmProto.Film value) {
        if (filmBuilder_ == null) {
          if (film_ != null) {
            film_ =
              org.akhq.utils.FilmProto.Film.newBuilder(film_).mergeFrom(value).buildPartial();
          } else {
            film_ = value;
          }
          onChanged();
        } else {
          filmBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public Builder clearFilm() {
        if (filmBuilder_ == null) {
          film_ = null;
          onChanged();
        } else {
          film_ = null;
          filmBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public org.akhq.utils.FilmProto.Film.Builder getFilmBuilder() {
        
        onChanged();
        return getFilmFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      public org.akhq.utils.FilmProto.FilmOrBuilder getFilmOrBuilder() {
        if (filmBuilder_ != null) {
          return filmBuilder_.getMessageOrBuilder();
        } else {
          return film_ == null ?
              org.akhq.utils.FilmProto.Film.getDefaultInstance() : film_;
        }
      }
      /**
       * <code>.org.akhq.utils.Film film = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder> 
          getFilmFieldBuilder() {
        if (filmBuilder_ == null) {
          filmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.FilmProto.Film, org.akhq.utils.FilmProto.Film.Builder, org.akhq.utils.FilmProto.FilmOrBuilder>(
                  getFilm(),
                  getParentForChildren(),
                  isClean());
          film_ = null;
        }
        return filmBuilder_;
      }

      private org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside complex_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside, org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.Builder, org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutsideOrBuilder> complexBuilder_;
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       * @return Whether the complex field is set.
       */
      public boolean hasComplex() {
        return complexBuilder_ != null || complex_ != null;
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       * @return The complex.
       */
      public org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside getComplex() {
        if (complexBuilder_ == null) {
          return complex_ == null ? org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.getDefaultInstance() : complex_;
        } else {
          return complexBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      public Builder setComplex(org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside value) {
        if (complexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          complex_ = value;
          onChanged();
        } else {
          complexBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      public Builder setComplex(
          org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.Builder builderForValue) {
        if (complexBuilder_ == null) {
          complex_ = builderForValue.build();
          onChanged();
        } else {
          complexBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      public Builder mergeComplex(org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside value) {
        if (complexBuilder_ == null) {
          if (complex_ != null) {
            complex_ =
              org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.newBuilder(complex_).mergeFrom(value).buildPartial();
          } else {
            complex_ = value;
          }
          onChanged();
        } else {
          complexBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      public Builder clearComplex() {
        if (complexBuilder_ == null) {
          complex_ = null;
          onChanged();
        } else {
          complex_ = null;
          complexBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      public org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.Builder getComplexBuilder() {
        
        onChanged();
        return getComplexFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      public org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutsideOrBuilder getComplexOrBuilder() {
        if (complexBuilder_ != null) {
          return complexBuilder_.getMessageOrBuilder();
        } else {
          return complex_ == null ?
              org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.getDefaultInstance() : complex_;
        }
      }
      /**
       * <code>.org.akhq.utils.ComplexWithBookOutside complex = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside, org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.Builder, org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutsideOrBuilder> 
          getComplexFieldBuilder() {
        if (complexBuilder_ == null) {
          complexBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside, org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutside.Builder, org.akhq.utils.ComplexWithBookOutsideProto.ComplexWithBookOutsideOrBuilder>(
                  getComplex(),
                  getParentForChildren(),
                  isClean());
          complex_ = null;
        }
        return complexBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.akhq.utils.MultipleLayerComplex)
    }

    // @@protoc_insertion_point(class_scope:org.akhq.utils.MultipleLayerComplex)
    private static final org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex();
    }

    public static org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipleLayerComplex>
        PARSER = new com.google.protobuf.AbstractParser<MultipleLayerComplex>() {
      @java.lang.Override
      public MultipleLayerComplex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultipleLayerComplex(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultipleLayerComplex> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipleLayerComplex> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.akhq.utils.MultipleLayerComplexProto.MultipleLayerComplex getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_akhq_utils_MultipleLayerComplex_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_akhq_utils_MultipleLayerComplex_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032multipleLayerComplex.proto\022\016org.akhq.u" +
      "tils\032\013album.proto\032\nfilm.proto\032\034complexWi" +
      "thBookOutside.proto\"\231\001\n\024MultipleLayerCom" +
      "plex\022$\n\005album\030\001 \001(\0132\025.org.akhq.utils.Alb" +
      "um\022\"\n\004film\030\002 \001(\0132\024.org.akhq.utils.Film\0227" +
      "\n\007complex\030\003 \001(\0132&.org.akhq.utils.Complex" +
      "WithBookOutsideB+\n\016org.akhq.utilsB\031Multi" +
      "pleLayerComplexProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.akhq.utils.AlbumProto.getDescriptor(),
          org.akhq.utils.FilmProto.getDescriptor(),
          org.akhq.utils.ComplexWithBookOutsideProto.getDescriptor(),
        });
    internal_static_org_akhq_utils_MultipleLayerComplex_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_akhq_utils_MultipleLayerComplex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_akhq_utils_MultipleLayerComplex_descriptor,
        new java.lang.String[] { "Album", "Film", "Complex", });
    org.akhq.utils.AlbumProto.getDescriptor();
    org.akhq.utils.FilmProto.getDescriptor();
    org.akhq.utils.ComplexWithBookOutsideProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
