name: Main

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Helm charts
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          charts-folder: "helm"
          deploy-branch: helm

      # Web site
      - name: Contributor
        run: |
          npm i github-contributors-list
          node_modules/.bin/githubcontrib --repo kafkahq --owner tchiotludo --format html --sortOrder desc > docs/contributors.html

      # Clone helm charts
      - name: Clone helm charts
        uses: actions/checkout@v2
        with:
          ref: helm
          path: tmp-helm

      # Web site
      - name: Add helm charts
        run: |
          rm -rf tmp-helm/.git
          cp -R tmp-helm/* docs/
          echo "akhq.io" > docs/CNAME

      # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: docs/

      # Slack
      - name: Slack notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          username: Github Actions
          icon_emoji: ':octocat:'
          channel: '#akhq'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
