name: Docs

on:
  push:
    branches:
      - dev
  repository_dispatch:
    types: [ akhq-release-docs ]

jobs:
  check:
    name: Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.client_payload.sha || github.sha }}

      # Setup
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      # Build
      - name: Build
        working-directory: docs
        run: |
          npm install
          node_modules/.bin/githubcontrib --repo akhq --owner tchiotludo --format html --sortOrder desc > .vuepress/public/contributors.html
          npm run build
          echo "akhq.io" > .vuepress/dist/CNAME

      # Clone helm charts
      - name: Clone helm charts
        uses: actions/checkout@v7
        with:
          ref: helm
          path: tmp-helm

      # Add helm charts
      - name: Add helm charts
        run: |
          rm -rf tmp-helm/.git
          cp -R tmp-helm/* docs/.vuepress/dist/

      # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist/

      # Slack
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          username: Github Actions
          icon_emoji: ':github-actions:'
          channel: 'C03H9CEBGS2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
